from pprint import pprint

text = '''
The Fool|U|Kind of like that feeling you get the morning of the first day of school, there's nothing like the sense that you're about to embark on a new adventure. You're feeling that right now: the vast possibilities of the roads you haven't taken yet, just on the horizon. Go into it with an open mind and an open heart (cheesy, but so is taking a leap!). Could there be bumps in the road you haven't planned for? Mmmmm maybe most definitely. But hey, don't worry about that now! Ignorance is bliss!|Innocence|New Beginnings|Spontaneity||
The Fool|R|You know when you have this idea, and you know it's awesome, and you know it's gonna change the world, or at the very least your world, but something is stopping you from putting it on the page? You're pumping the brakes before you've even gotten started, but why? Take a step back from the expectations and let yourself reflect on what's stoppin' ya from moving forward. Alternately, the reversed Fool can be telling you that you're driving TOO FAST. Don't book a show before you've even finished the lyrics of your songs. Don't count your Triceratops eggs before they've hatched. In other words: don't let your eagerness make you turn your back on the potential consequences of your actions. |Recklessness|Risk Taking |Foolhardiness||
The Magician|U|This is a powerful card, friend! You've planted the seeds of an idea, and with that comes the knowledge that you have the tools to make it possible. But it's up to you to make sure that you're following this particular path for the right reasons: is it important to you in your heart, in your soul? Or do you just want to get famous, become a rock and roll legend and never have to go to school again or something? Concentrate on whatever this seed is, whether it's a friendship or a creative endeavor, and really commit to understanding what you want it to grow into in the future.|Creation|Manifestation|Inspired Action||
The Magician|R|It's not that you're not making progress on your goals, it's just that maybe you're still uncertain on how to get there. You're flapping your wings a bit, or you're treading water. Maybe you've lost sight of the deeper meaning behind something that was once really compelling to you, or you're finding that you're focusing too much on how to do something, instead of why you're doing it. You have so much to give to the world, but you have to believe in yourself first. Alternately, this card holds an understanding that there may be—however unintentional—some underlying malice to something in your actions. You may be using your authority or knowledge for self-gain at the expense of others. Keep an eye on your priorities and make sure you're acting with generosity and kindness towards those around you!|Illusion|Manipulation|Untapped Talents||
The High Priestess|U|Look, I know this stuff can get a bit hippie-dippy but stick with me: the High Priestess is here to tell you that right now is a good time to tap into your inner emotional gunk. Clear off the cobwebs of your intuition and try trusting it! You could start journaling, or meditation, or sitting with your thoughts on top of a hill while staring into the middle distance. Your subconscious is trying to pass you a note in the middle of class: will you take a minute to read it? You might learn something about yourself.|Sacred Energy|Subconscious Mind|Intuition||
The High Priestess|R|If the upright High Priestess is about submerging yourself in the subconscious, its reversed position is letting you know that you might be struggling with trusting your ability to flap your tail in those waters. Something is holding you back...  maybe you're keeping something from yourself, or maybe you're afraid of what you might find when you stop rejecting your intuition. Believe in your ability to look within yourself for answers. They're often there.|Secrets|Disconnection from the Self|Repressed Feelings||
The Empress|U|Alright so the ole' Tarot set is getting a bit binary here with the Empress and the Emperor, but let's try to look at it as a connection to certain types of energies instead. The Empress is a card of riches, whatever that may mean to you. It's a buffet of gratitude, a bite of self-expression, a nom of creative discovery. If this has made you hungry, go enjoy a gratuitous meal and really bask in it: that type of abundance is what the Empress is all about! Things you have been dreaming of are coming into fruition. Enjoy them with your loved ones, or reflect on what you're thankful for on your own in the woods or at the beach. |Nature|Abundance|Feminine Energy||
The Empress|R|Maybe you've been inside too long, or maybe you're just in a rut, but the reversed Empress is letting you know, you could use a little more focus on yourself. This might be a time to do something just for you: write a song you don't need to show anyone, go for a walk, do 25 raptor-jacks out in the park just for the kick of it. You might just jostle out a few ideas, or shift out of the creative block you've been feeling. |Dependence|Creative Block|Emptiness||
The Emperor|U|Like we said with the Empress, the Tarot gets a bit binary here with the Empress and the Emperor, but I know you contain multitudes so don't even worry about it. The Emperor deals with a feeling of stability and structure. It may be letting you know that you're feeling good about a leadership role, or that you feel particularly equipped to deal with conflict. Like a good student body president or a particularly adept lunch lady, you are ruling with wisdom and organization. Use this organization to break down complex issues into bite-sized nuggets, and once you've learned how to do it, pass that info along to someone else!|Authority|Structure|Masculine Energy||
The Emperor|R|Someone in another universe once said that with great power comes great responsibility. Don't ask me what universe, it came to me in a dream! What's important here is looking at your own relationship to power—whether you're not exerting it enough and feeling your tail get trod on or you're exerting it too much and roaring in people's faces, you owe it to yourself and those around you to think about how you wield authority. Is someone or something making you feel like you can't speak up? Are you having trouble giving up control or delegating? Power is a, well, powerful thing. It must be distributed fairly and carefully.|Domination|Lack of Discipline|Aloofness||
The Hierophant|U|Even though the Hierophant has its origins in religion and spiritual beliefs, in an interpersonal, day-to-day sort of way, it's more about engrained knowledge and a tried and true system that's been working for you. It's about acquiring wisdom from someone or something you trust and believe in. And if you are spiritually leaning... hi, hello, welcome to my home: the Hierophant is also asking you to honor that spirituality and any rituals that may come with it. |Conformity|Tradition|Morality and Ethics||
The Hierophant|R|So the upright Hierophant is about institutions that you trust and feel held by and the wisdom that comes with learning from someone. WELL FLIP THE TABLE 'cause when the Hierophant is reversed it's about being your own teacher, headbutting convention, and going your own way. When your teachers don't believe you or your parents keep trying to control you or your boss is making you feel like you're bad at your job, you have to say, "I'm going to grab life by the horns and break outta this joint!" This joint being societal norms. ;)|Freedom|Challenging Institutions|New Approaches||
The Lovers|U|Ooooh, you are out here vibing with someone!!! (Please dish on who it is, I won't gossip.) I for one hope you are getting to engage in a little... anky-panky. You're an ankylosaurus, right? Don't throw your shoe at me! Look, the Lovers don't have to be romantic in nature. You could be on the same wavelength with a bandmate, or a coworker, or a best friend. At the end of the day, it's about a connection forged in trust and love. Someone you can tell everything to, even your most vulnerable truths. You can also be forging a deeper connection to yourself, and looking at the dualities within you that create a more cohesive whole. Deep, I know.|Partnerships|Harmony|Duality||
The Lovers|R|Maybe you're out of sync with the people around you, maybe you're having trouble communicating, or maybe you're in a relationship that's feeling kind of one-sided... regardless, something feels off. So what's a lovelorn dino to do in such a situation? I recommend taking a look under your headplate and seeing if you can find the source of the imbalance. If the conflict is interpersonal, maybe there is room for mutual growth. If the conflict is with yourself, this may be a time to reflect on how you can find balance with the many facets that make you you!|Disharmony|Imbalance|One-Sidedness||
The Chariot|U|Grab that tyrannosaurus by the reins and take charge!! The Chariot signifies that you have found order and understanding on a subject in your life and are now ready for action. The energy here is all about keeping you on focus, keeping you bold, and reminding you to have faith in yourself. Now is a time of determination!! Alternately, this card may signify actual travel, and if that's the case, I call shotgun.|Action|Determination|Willpower||
The Chariot|R|Hold your horns there, friend. You gotta check the map for directions before you get on the highway. The reversed Chariot is telling you that you may not have as firm of a grasp on the direction a project is heading in than you thought and that ya might want to take a second look. That might be too hard to do right now, but that's normal! Bumps in the road are a part of life. Maybe you're having trouble seeing a path ahead because you have two separate ideas pulling you in different directions. You gotta get those wheels facing in the same direction or you won't go anywhere. The extended metaphor is rolling away from me, somebody stop it!!!|Lack of Direction|Opposition|Intensity||
Strength|U|Inner strength is so hot! There's nothing like when you meet someone and you can tell their emotional core is rooted—they're not gonna blow away in a storm. Too metaphorical? The Strength card is about that knowledge that you are capable or determined, and calm in that determination. Your power is not aggressive, but persuasive, you are alluring right now and effortlessly in control. You don't need to grab a sabretooth by the fangs, because it's already eating out of your hand.|Inner Strength|Persuasion|Compassion||
Strength|R|When we doubt ourselves, it can make us lose balance. It's disorienting and exhausting to lose touch with what we most love about ourselves, and it can affect our self-esteem. Try to touch base with all the times you totally crushed it. You already know you rule—a moment in time where you're not sure about it will pass. Try to be kind to yourself; just because you didn't get an A on your English assignment doesn't mean you're a failure. Lay your weary self to rest for a bit! You deserve it.|Self Doubt|Low Energy|Insecurity||
The Hermit|U|Think druid in a game of L&L: off in nature, communing with the griffinflies, wearing your cloak, and listening to the sounds of a distant waterfall. You're on your own, but certainly not in a bad way. You're simply vibing with yourself and ruminating on your place in the universe. You're getting to know yourself better on your own terms, not those set by society (individualism, capitalism, greed, all that bad stuff!) and it's giving you the guidance you deserve. Be your own pathfinder.|Introspection|Inner Guidance|Being Alone||
The Hermit|R|Your phone and your laptop are bleep blooping with notifications, the TV's on, and for some reason the radio's blasting from the other room. It's enough to give even the most hardcore multitasker a headache! You're juggling more tasks than an Arthropleura has legs! All of this is sending you mixed signals, and you're unable to focus on what's important to you. Try to pluck off a few of your tasks for right now and focus on yourself and what's most important to you. You can get back to the rest later. Alternately, you may be feeling intentionally left out of things, or feeling alone. If that's the case, maybe pick up the phone and call a loved one you haven't been in touch with in a while. It'll probably do you both some good!|Isolation|Withdrawal|Lost Your Way||
Wheel of Fortune|U|Ever since that like, ancient dinosaur or whoever invented the wheel, we have understood that what goes around comes around. And that whatever's down will come up again! The Wheel of Fortune tells you to keep sight of those natural cycles, and the changes they bring. If you're on a roll (heh...) right now, then appreciate that feeling as something that may not last forever. If you're stuck in the mud, just know you won't be there forever. This card is about going with the flow, and letting the universe guide you as much as possible. 😎 This may be a big turning point for you.|Cycles|Destiny|Turning Point||
Wheel of Fortune|R|You can't stop a rolling wheel! Well, actually I guess you can but it's not a good idea. You ever tried to grab someone's bike while they were ridin' by you? Ya. Not good. You can't stop the change that's already on its way, and you'll only hurt yourself by trying. Alternately, the reversed Wheel of Fortune shows bad luck that is out of your control and may be making you feel like you have nowhere to turn. But you could try to summon up a timeline of what got you here, and see how you can learn from past experiences. Maybe in identifying the patterns, you can make... A NEW WHEEL. A NEW FORTUNE. The power is in your hands.|Bad Luck|Clinging to Control|Resistance to Change||
Justice|U|You reap what you sow! Currently, I'm reaping some greens for my friend (she's a sauropod) from the conifers I planted. They're so pretty all bundled up in a little care package, I love it!! Omg sorry got carried away with garden talk... The Justice card tells you that a verdict is on its way. You're thinking of your past actions and wondering what the karmic retribution will be. Have you been sour to the people around you and are now feeling isolated? Maybe you've been kind to everyone as much as possible, even when it's been hard, and you're feeling the rewards that being fair and generous with people can bring.|Clarity|Truth|Cause and Effect||
Justice|R|You may have done something wrong, but for whatever reason, you can't own it. Your ego is making it so hard to take accountability. Maybe you don't even recognize that you've hurt someone, because you've been spinning your narrative out in your mind so much you fully believe it! Try acknowledging any and all internalized prejudices you may be holding, and really be honest with yourself about how your actions may be affecting others. Alternately, you may be going through a period in your life where you're being excessively hard on yourself, to the point where you've lost sight of objectivity. Either way, there is a sense of one-sidedness here, in one direction or another, and you need to find some harmony in your perspective on it.|Lack of Accountability|Dishonesty|Unfairness||
The Hanged Man|U|My best friend Sage always says, "If you're having trouble figuring something out, try a handstand!" It's about like, getting a new perspective? The Hanged Man always looks so freaky! But it's actually just about taking a breather on your journey. When you take a break sometimes new ideas flow through you, where there wasn't time or room for them to exist before. Don't push yourself when the world is asking you to pause, or you could risk giving yourself a real headache later down the road. Surrender to rest instead, and let the blood rush to your head with new ideas instead.|Letting Go|Surrender|New Perspectives||
The Hanged Man|R|You're not letting yourself take a break, but why? Don't you know that when you stop charging recklessly towards your goal, things can put themselves in focus more easily? Don't let life blur by you thoughtlessly when your body and mind are begging for a break. The reversed Hanged Man (so wait, would that just be like... a Standing Man?) can mean you did pause, or you did sacrifice something to a greater goal, and it didn't feel like it went anywhere. Try to forgive and forget, so you can more easily continue on your journey.|Inecision|Fear of Sacrifice|Delays||
Death|U|Everyone always looks at me like they just saw a ghost when I draw this card. There's nothing to fear, though! Ultimately all the Death card is trying to say is that change is coming. Ya, maybe that means closing a door, but maybe that door needs to close! We can't stay in high school forever, or stay the same dinos: we have to evolve. Something good is on the other side. And maybe that comes with some mourning, but as a wise philosopher once said, "Every new beginning comes from some other beginning's end." Mmm maybe that's from a song. Please don't sue me. |Endings|Metamorphosis |Transition||
Death|R|Let go or be dragged, that's what I always say! The reversed Death card is revealing to you that there's something from your past you're having trouble releasing. Maybe someone hurt you and that pain still lives inside you. Maybe you hurt someone and it's closing you off to the possibility of forgiveness. But holding on to stale food is only gonna stink up your emotional fridge! You don't want to become a fossil of your old self. Ungrip those talons, babes, surrender to the future, and fly!|Stagnation|Resistance|Fear of Change||
Temperance|U|You're smooth, you're zen, you're water dripping slowly in an Arganodus fish pond. It feels like even with a million things going on around you, you're able to remain calm and balanced. Maybe your friends are asking for your advice on a dispute because you're so objective and patient. You know nothing comes from rushing things, or trying to force someone to hatch who's not ready yet. You can hold on to many ideas at once right now, and blend them into something totally new. Like a divine smoothie.|Balance|Moderation|Patience||
Temperance|R|You're shaking your soul's bones back into the right position. It may be a bit uncomfortable, but it's needed! Maybe you've been bingeing anime for 3 days straight or maybe you've been spending too much time with dinos who deplete you of your energy. Whatever's been weighing you down, it's time to rid yourself of it. If you ignore the warning signs that something is off for too long, you'll risk feeling stuck, or your soul's misaligned bones will start to fossilize... you don't want a fossilized soul!!|Imbalance|Re-alignment|Extremes||
The Devil|U|Oh sweetie, you are going through it, aren't you! This card is revealing that the darker forces in your life are coming to the forefront and dominating you like lava covering the terrain of your soul. 💔 With toxic patterns and habits influencing your behavior, you may find yourself rehashing the same fights with a loved one, unable to stop yourself from making that little jab, or rolling your eyes, because you've gotten so used to your defenses that not having them up makes you feel like you're walking around without scales... just a raw nerve! An alternate interpretation of this card is that the time has come for you to have a little fun! If you're normally risk-averse, you could try playing with (safely) trying something new and unlike you. You may enjoy it!|Excess|Shadow Self|Playfulness||
The Devil|R|You're looking to plant a garden that you can truly tend to, where everything that you sow can live in harmony together. But before you can do that, you have to weed out the ferns to make space for what you really want to plant. Does my garden analogy make sense? Hee hee!! What I'm saying is there's some major emotional exploration that has to happen before you can get to where you're going. Some of that exploration may be of some pretty dark thoughts or fears: you may not realize you've been clipping your wings until you look back at them! |Release|Detachment|Exploring Dark Thoughts||
The Tower|U|It feels like the universe has or is about to throw you a real curve ball... the Tower is the tarot equivalent of trying to do the "rip the tablecloth off without disturbing the cutlery" trick and having the whole table fall down on you. Something is breaking down, and it's something you thought was stable. This sense of disintegration is good though (stick with me), because it may reveal some bogus assumptions you'd been making. You were flying too close to the sun, and while you may have experienced a setback, the Tower also represents epiphanies and new ways of thinking.|Upheaval|Chaos|Revelation||
The Tower|R|So where the upright Tower is very much about an unexpected occurrence, often outside your control, the reversed Tower shows you on the precipice of a personal evolution—if you can allow it into your life. You could be questioning a large part of your identity, or how you see others, or what you want for your future. I'm sure it's stomachache-inducing to think so much about that type of revelation, but it's an important step in your growth. There's no point in resisting it... oh ya, that's another meaning of this card by the way: a resistance to change, especially when you have a feeling it may be negative. Better to go headfirst into the challenge with your eyes open than get caught unawares by it!|Personal Transformation|Fear of Change|Crisis Averted||
The Star|U|Hoooo! You've been through the lava and you're still keeping cool. The Star, coming as the follow-up to the Tower, is about rest and renewal. It's about the understanding that even though you've had setbacks, you're still on your way up. You've lost a battle but you haven't lost sight of your dreams. Maybe you totally bombed on a college application essay, but there's another school you just know will want you. Or maybe you're just removing the protective plates that aren't serving you anymore in service of a more "you-ey" you. Hehe... "you-ey"|Hope|Purpose|Renewal||
The Star|R|You may have recently faced a major setback (remember, the Star card follows the Tower, which is all about setbacks with a capital S). You can't seem to take it all in: it doesn't feel fair. It may feel like the end of the world, or like you have nothing left to give. Try to have faith. Maybe it is the end of the world, but if it is, don't you owe it to yourself to take care of yourself and the ones you love? Try to engage with the things that make you feel present in whatever is most important to you. All is not lost!|Discouragement|Insecurity|Disconnection||
The Moon|U|A lot of us can put on a brave face in front of others, but when we're alone in our room and the lights are off, all we're left with are our anxieties and worries. Those fears could be about the past, something stupid we said or how we laughed in that weird way in homeroom. Or it could be a worry for the uncertainty of the future... But being in the dark isn't something you should fear! Harness that solitude and use it for introspection! The night air in Caldera Bay is as re-invigorating as anything I've ever felt; go for a walk and see if it gives you a fresh, crisp insight on your issues. And let the night guide you into fruitful dreams that may shed light on your subconscious. 😴 Just don't lose your way!|Illusion|Intution|Anxiety||
The Moon|R|When the Moon card is reversed, it means you've been in your head for so long, you don't know which way is up—you may be in denial about something, or convinced that something is going on based on nothing but your gut.  But while you're all like, "La la la la la I'm not listening to you, reality," you may be missing out on what's really important. It's not that you need to stop listening to your subconsious, it just means your subconscious could use a bit of a leash to the real world.|Repressed Emotion|Fear|Confusion||
The Sun|U|The sun is shining, you're relaxing, the birds are chirping, and it feels like everything's comin' up.... YOU! The sun is a sign that your inner warmth and happiness is taking center stage, and that joyous vibe is infectious! You're shootin' rays of positivity out of your headplate! Maybe you just gave up smoking and you're full of a renewed sense of energy, or maybe you just learned a new skill and are bursting at the scales to show it off. Alternately, you could be going through a hard time, and the Sun card is here to give you a pep talk, that the sun is rising for you soon. Just hold on!|Positivity|Vitality|Joy||
The Sun|R|Sigh.... you know when you plan a beach trip and then the day of it's suddenly like, totally rainy and cloudy and you just wanna stomp your feet and chomp someone's head off? The reversed Sun card is the rain on your parade, the C you got in Math class, the mites on your favorite plant's leaves! Any of those things are enough to discourage someone, and it's normal to feel disappointed or pessimistic. But you know what all those things are? Temporary setbacks! You'll find your way through the fog soon enough, sweetie!|Negativity|Inner Child|Sadness||
Judgement|U|Ahh, you may be getting close to a milestone in a personal journey. You've put together a bunch of disparate notes into a beautiful song, gathered the ingredients together for a delicious meal. You're finding yourself in a period of acceptance and understanding. You can see your mistakes and your triumphs in the distance behind you, and you're taking this time to share that love and peace with your loved ones. What do we owe each other at the end of a journey? What do we need from each other to keep soaring even higher?|Inner Calling|Reflection|Rebirth||
Judgement|R|You're seeing a lot of disparate puzzle pieces, but unfortunately the puzzle is of a blue sky, so it's a bit hard to put together. No matter! You know what you're doing, and I believe in you! But first you have to actually look at your journey so far, and what you still have to do. You can't forgive yourself for past mistakes if you don't take accountability for them. You can't achieve your goals if you're constantly doubting yourself. Easier said than done, I know, but looking at your life and your choices—really digging in the mud of it—is the only way to come to a place of peace.|Inner Critic|Self-doubt|Avoidance||
The World|U|You are at the top of the volcano! You are a mighty beast! You are at the end of a montage of a lot of hard work and close-ups of you looking cute and determined, and now everyone around you is clapping and throwing their hats in the air! You feel a sense of completion and extreme purpose!! Ok, maybe it doesn't feel as momentous as all that, but it's like, definitely the end of an era. Whether it's graduation, a creative accomplishment, or a relationship breakthrough, you are achieving something long envisioned. If you're not quite at this point of accomplishment, this card is letting you know that now is the time to get your microraptors in a row and reflect on what has brought you to where you are. Maybe that's just the push you need to bring yourself full circle.|Accomplishment|Travel|Fulfillment||
The World|R|Sometimes we crave closure on a situation, but we're not taking all the steps we could be to get there. We may be waiting on someone else to do the work we know is ours to do, or feeling like our goal is too large or nebulous to see an end to. This card is letting us know that we may need to do some personal work—whether it's through writing down your feelings or talking to someone—to sharpen our understanding of where we want to be. When the World card is reversed, it can mean that you're at the end of a marathon of sorts, but for whatever reason, you can't get your claws over the finish line. But think of what's on the other side!! Gatorade! High fives! Celebration! So don't stop now, friend, keep going!|Delays|Incomplete Goals|Unfulfillment||'''

lines = text.split('\n')
for i, line in enumerate(lines):
    if not line:
        continue
    name, orientation, text, *tags = line.split('|')
    url = ''
    n = (i-1)//2
    tags = [t for t in tags if t]
    # data = {
    #     'name': name,
    #     'orientation': orientation,
    #     'tags': tags,
    #     'image': '',
    #     'text': text
    # }
    # print(str(data) + ',')

    data = [n, name, orientation, tags, text, url]
    print(data)



